config/routes.rb
Rails.application.routes.draw do

  resources :tasks

  root 'tasks#index'
  #details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
    @task = Task.new
  end

  def show
  end

  def create
    @task = Task.new(task_params)
    @tasks = Task.all
    if @task.save
      redirect_to tasks_path
    else
      flash.now[:alert] = @task.errors.full_messages
      render :index
    end
  end

  def edit
  end

  def update
    if @task.update(task_params)
      redirect_to tasks_path
    else
      flash.now[:alert] = @task.errors.full_messages
      render :edit
    end
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :body)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DaisukeKuraishiTask</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>書籍更新フォーム</h1>

<% if flash["alert"].present? %>
  <div class="error_color">
    <h3>[エラー内容]</h3>
      <% flash["alert"].each do |value| %>
        <%= content_tag(:div, value) %>
      <% end %>
  </div>
<% end %>

<%= form_with model: @task, local: true do |form| %>
  <p>
    タイトル<br>
      <%= form.text_field :title %>
  </p>
  <p>
    内容<br>
      <%= form.text_area :body %>
  </p>
  <%= form.submit "更新" %>
<% end %>

app/views/tasks/index.html.erb
<h1>タスク一覧</h1>
<ul>
  <% @tasks = Task.all %>
  <% @tasks.each do |task| %>
    <li><%= link_to task.title, task_path(task) %>  |
    <%= link_to "削除", task_path(task), method: :delete %></li>
  <% end %>
</ul>

<hr>

<h3>タスク登録</h3>

<% if flash["alert"].present? %>
  <div class="error_color">
    <h3>[エラー内容]</h3>
    <% flash["alert"].each do |value| %>
      <%= content_tag(:div, value) %>
    <% end %>
  </div>
<% end %>

<%= form_with model: @task, local: true do |form| %>
  <p>
    タイトル<br>
    <%= form.text_field :title %>
  </p>
  <p>
    内容<br>
    <%= form.text_area :body %>
  </p>

  <%= form.submit "登録" %>

<% end %>

app/views/tasks/show.html.erb
<p>
  <b>タイトル：<%= @task.title %></b>
</p>

<p>
  <b>内容：<%= @task.body %></b>
</p>


<%= link_to "編集", edit_task_path(@task) %>

<%= link_to "削除", task_path(@task), method: :delete %>

<%= link_to "一覧に戻る", tasks_path(@task) %>